# Generated by Django 5.1 on 2024-08-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='commnent',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
