# Generated by Django 5.1 on 2024-08-22 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('degree', models.CharField(choices=[(1, 'riazi'), ('physics', 2), (3, 'dini'), (4, 'eghtesad'), ('danesh', 5), (6, 'olom')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='proffesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[(1, 'sikl'), (2, 'diplom'), (3, 'kardani'), ('karshenasi', 4), ('karshenasi arshad', 5), ('pro', 6)], default={'diplom', 2}, max_length=20)),
                ('lesson', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userKhodam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('createdtime', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=20)),
                ('proffesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.proffesor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.userkhodam')),
            ],
        ),
        migrations.AddField(
            model_name='proffesor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.userkhodam'),
        ),
    ]
