# Generated by Django 5.1 on 2024-08-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='degree',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proffesor',
            name='degree',
            field=models.CharField(choices=[(1, 'sikl'), (2, 'diplom'), ('kardani', 3), ('karshenasi', 4), ('karshenasi arshad', 5), ('pro', 6)], default={'diplom', 2}, max_length=20),
        ),
        migrations.AlterField(
            model_name='userkhodam',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
