# Generated by Django 5.1 on 2024-08-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_lesson_degree_alter_lesson_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proffesor',
            name='degree',
            field=models.CharField(choices=[(1, 'sikl'), (2, 'diplom'), ('kardani', 3), (4, 'karshenasi'), (5, 'karshenasi arshad'), ('pro', 6)], default={'diplom', 2}, max_length=20),
        ),
    ]
