# Generated by Django 5.1 on 2024-08-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_proffesor_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proffesor',
            name='degree',
            field=models.CharField(choices=[(1, 'sikl'), (2, 'diplom'), (3, 'kardani'), ('karshenasi', 4), ('karshenasi arshad', 5), ('pro', 6)], default={'diplom', 2}, max_length=20),
        ),
    ]
