# Generated by Django 5.1 on 2024-08-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_proffesor_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proffesor',
            name='degree',
            field=models.CharField(choices=[('sikl1', 'sikl'), ('diplom', 'diplom1'), ('kardani1', 'kardani'), ('karshenasi', 'karshenasi1'), ('karshenasi arshad', 'karshenasi arshad1'), ('pro', 'pro1')], max_length=20),
        ),
    ]
