# Generated by Django 5.1 on 2024-08-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_proffesor_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='proffesor',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proffesor',
            name='degree',
            field=models.CharField(choices=[('sikl', 'sikl1'), ('diplom', 'diplom1'), ('kardani1', 'kardani'), ('karshenasi1', 'karshenasi'), ('karshenasi arshad1', 'karshenasi arshad'), ('pro1', 'pro')], max_length=20),
        ),
    ]
