# Generated by Django 5.1 on 2024-08-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_proffesor_name_alter_proffesor_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proffesor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proffesor',
            name='degree',
            field=models.CharField(choices=[('sikl1', 'sikl'), ('diplom1', 'diplom'), ('kardani1', 'kardani'), ('karshenasi1', 'karshenasi'), ('karshenasi arshad', 'karshenasi arshad1'), ('pro1', 'pro')], max_length=20),
        ),
    ]
